src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $message;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'boolean')]
    private $is_read = 0;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'sent')]
    #[ORM\JoinColumn(nullable: false)]
    private $sender;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'received')]
    #[ORM\JoinColumn(nullable: false)]
    private $recipient;


    public function __construct(){
        $this->created_at = new \DateTime();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;

use App\Entity\Messages;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextAreaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class, [
                "class" => User::class,
                "choice_label"=>"email",
                "attr"=>[
                    "class"=>"form-controll"
                ]
            ])
            ->add('envoyer', SubmitType::class, [
                "attr"=>[
                    "class"=>"btn btn-primary"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessageType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;


class MessageController extends AbstractController
{
    #[Route('/message', name: 'message')]
    public function index(): Response
    {
        return $this->render('message/index.html.twig', [
            'controller_name' => 'MessageController',
        ]);
    }

    #[Route('/send', name:'send')]
    public function send(Request $request, EntityManagerInterface $em): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessageType::class, $message);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($this->getUser());

            $em->persist($message);
            $em->flush();

            $this->addFlash('message', 'Message envoyé');

            return $this->redirectToRoute('message');
        }

        return $this->render("message/send.html.twig", [
            'form' =>$form->createView()
        ]);
    }

    #[Route('/received', name: 'received')]
    public function received(): Response
    {
        return $this->render('message/received.html.twig',);
    }

    #[Route('/read{id}', name: 'read')]
    public function read(Messages $message, EntityManagerInterface $em): Response
    {
        $message->setIsRead(true);

        $em->persist($message);
        $em->flush();

        return $this->render('message/read.html.twig', compact("message"));
    }

    #[Route('/delete/{id}', name: 'delete')]
    public function delete(Messages $message, EntityManagerInterface $em): Response
    {
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute('received');
    }

    #[Route('/sent', name: 'sent')]
    public function sent(): Response
    {
        return $this->render('message/sent.html.twig',);
    }

}

templates/message/index.html.twig
{% extends 'base.html.twig' %}
{% block title %} Messagerie {% endblock %}


{% block body %}
{% include 'partials/_navbar.html.twig' %}

<style>
    .container{
        height: 100vh;
        margin-top: 100px;
        width:900px;
    }
    .offcanvas-body{
       margin-top: 50px;
       font-size: 16px;
    }
    .list a{
        text-decoration: none;
        color: black;
    }
</style>

      
{% for message in app.flashes("message") %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" area-label="close"></button>
</div>
{% endfor %}

<div class="container">
    <h1>Messagerie</h1>
    <p>Reçus : {{ app.user.received | length }} </p>
    <p>Envoyés : {{ app.user.sent| length }}</p>
    <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Voir mes dossiers
      </a>

      <a class="btn btn-primary" href="{{ path('send') }}" role="button">
        Envoyer un message
      </a>
      
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
         <div class="list">
             <a href="{{ path('message') }}">Acceuil</a>
         </div><hr>
         <div class="list">
            <a href="{{ path('received') }}">Boîte de récéption {{ app.user.received | length }}</a>
        </div><hr>
        <div class="list">
            <a href="{{ path('sent') }}">Elements envoyés {{ app.user.sent| length }}</a>
        </div><hr>
        </div>
      </div>

</div>

{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock %}

templates/message/read.html.twig
{% extends 'base.html.twig' %}
{% block title %} Messagerie {% endblock %}


{% block body %}
{% include 'partials/_navbar.html.twig' %}

<style>
    .container{
        height: 100vh;
        margin-top: 100px;
        width:900px;
    }
    .offcanvas-body{
       margin-top: 50px;
       font-size: 16px;
    }
    .list a{
        text-decoration: none;
        color: black;
    }

    .content-message{
        background-color:#b5cde0;
        padding: 5px;
        margin-top: 10px;
    }

    .col{
    }
</style>

      
{% for message in app.flashes("message") %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" area-label="close"></button>
</div>
{% endfor %}

<div class="container">
    <h1>Messagerie</h1>
    <h2>{{ message.title }}</h2>
    <p>Message de : {{ message.sender.email }}</p>
    <p>{{ message.createdAt|date }}</p>
    <div>{{ message.message }}</div>

    <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Voir mes dossiers
      </a>

      <a class="btn btn-primary" href="{{ path('received') }}" role="button">
        Retour à la boite de réception
      </a>
      

 
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
         <div class="list">
             <a href="{{ path('message') }}">Acceuil</a>
         </div><hr>
         <div class="list">
            <a href="{{ path('received') }}">Boîte de récéption {{ app.user.received | length }}</a>
        </div><hr>
        <div class="list">
            <a href="{{ path('sent') }}">Elements envoyés {{ app.user.sent | length }}</a>
        </div><hr>
        </div>
      </div>

    </div>

{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock %}

templates/message/received.html.twig
{% extends 'base.html.twig' %}
{% block title %} Messagerie {% endblock %}


{% block body %}
{% include 'partials/_navbar.html.twig' %}

<style>
    .container{
        height: 100vh;
        margin-top: 100px;
        width:900px;
    }
    .offcanvas-body{
       margin-top: 50px;
       font-size: 16px;
    }
    .list a{
        text-decoration: none;
        color: black;
    }

    .content-message{
        background-color:#b5cde0;
        padding: 5px;
        margin-top: 10px;
    }

    a svg{
        color: rgb(15, 15, 109);
    }

    .col{
    }
</style>

      
{% for message in app.flashes("message") %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" area-label="close"></button>
</div>
{% endfor %}

<div class="container">
    <h1>Messagerie</h1>
    <h2>Boîte de réception : </h2>
    <p>Vous avez reçu {{ app.user.received | length }} messages</p>

    <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Voir mes dossiers
      </a>

      <a class="btn btn-primary" href="{{ path('send') }}" role="button">
        Envoyer un message
      </a>
      


    {% for message in app.user.received %}

        {% if message.isRead == 0 %}
            {% set bold = "fw-bold" %}
        {% else %}
            {% set bold = "" %}     
        {% endif %}

        <div class="content-message">
            <div class="col {{ bold }}"> De  : {{ message.sender.email}}</div>
            <div class="col {{ bold }}"> Sujet : <a href="{{ path('read', {id:message.id}) }}">{{ message.title}}</a></div>
            <div class="col {{ bold }}"> Date : {{ message.createdAt|date}}</div>
            <div class="col">
                <a href="{{ path ('delete', {id: message.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z"/>
                  </svg></a>
            </div>
        </div>

    {% endfor %}

 
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
         <div class="list">
             <a href="{{ path('message') }}">Acceuil</a>
         </div><hr>
         <div class="list">
            <a href="{{ path('received') }}">Boîte de récéption {{ app.user.received | length }}</a>
        </div><hr>
        <div class="list">
            <a href="{{ path('sent') }}">Elements envoyés {{ app.user.sent| length }}</a>
        </div><hr>
        </div>
      </div>

    </div>

{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock %}

templates/message/send.html.twig
{% extends 'base.html.twig' %}
{% block title %} Messagerie {% endblock %}


{% block body %}
{% include 'partials/_navbar.html.twig' %}

<style>
    .container{
        height: 100vh;
        margin-top: 100px;
        width:900px;
    }

    .offcanvas-body{
       margin-top: 50px;
       font-size: 16px;
    }
    .list a{
        text-decoration: none;
        color: black;
    }
</style>

<div class="container">
    <h1>Envoyer un message : </h1>

    {{ form(form) }}

    <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Voir mes dossiers
      </a>

      
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
         <div class="list">
             <a href="{{ path('message') }}">Acceuil</a>
         </div><hr>
         <div class="list">
            <a href="{{ path('message') }}">Boîte de récéption {{ app.user.received | length }}</a>
        </div><hr>
        <div class="list">
            <a href="{{ path('sent') }}">Elements envoyés</a>
        </div><hr>
        </div>
      </div>

</div>

{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock %}

templates/message/sent.html.twig
{% extends 'base.html.twig' %}
{% block title %} Messagerie {% endblock %}


{% block body %}
{% include 'partials/_navbar.html.twig' %}

<style>
    .container{
        height: 100vh;
        margin-top: 100px;
        width:900px;
    }
    .offcanvas-body{
       margin-top: 50px;
       font-size: 16px;
    }
    .list a{
        text-decoration: none;
        color: black;
    }

    .content-message{
        background-color:#b5cde0;
        padding: 5px;
        margin-top: 10px;
    }

    a svg{
        color: rgb(15, 15, 109);
    }

    .content-all{
        margin-bottom: 40px;
    }
</style>

      
{% for message in app.flashes("message") %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" area-label="close"></button>
</div>
{% endfor %}

<div class="container">
    <h1>Messagerie</h1>
    <h2>Boîte de réception : </h2>
    <p>Vous avez envoyé {{ app.user.received | length }} messages</p>

    <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
        Voir mes dossiers
      </a>

      <a class="btn btn-primary" href="{{ path('send') }}" role="button">
        Envoyer un message
      </a>
      
<div class="content-all">

    {% for message in app.user.sent %}

        {% if message.isRead == 0 %}
            {% set bold = "fw-bold" %}
        {% else %}
            {% set bold = "" %}     
        {% endif %}

        <div class="content-message">
            <div class="col {{ bold }}"> De  : {{ message.sender.email}}</div>
            <div class="col {{ bold }}"> Sujet : <a href="{{ path('read', {id:message.id}) }}">{{ message.title}}</a></div>
            <div class="col {{ bold }}"> Date : {{ message.createdAt|date}}</div>
            <div class="col">
                <a href="{{ path ('delete', {id: message.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z"/>
                  </svg></a>
            </div>
        </div>
   
    {% endfor %}
 </div>
 
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        <div class="offcanvas-header">
          <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
         <div class="list">
             <a href="{{ path('message') }}">Acceuil</a>
         </div><hr>
         <div class="list">
            <a href="{{ path('received') }}">Boîte de récéption {{ app.user.received | length }}</a>
        </div><hr>
        <div class="list">
            <a href="{{ path('sent') }}">Elements envoyés {{ app.user.sent| length }}</a>
        </div><hr>
        </div>
      </div>

    </div>

{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
{% endblock %}